### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ngeorgieff** [BamaRayne/Echosistant#52] opened 2016-12-28 18:01 UTC
Hi,

I'm getting error "TypeError: Cannot read property 'type' of undefined" when I enter Utterance "Repeat Last Message".

Lambda request is:
`{
  "session": {
    "sessionId": "SessionId.4c51bc2e-d897-48ff-90df-0aa7a78b9b36",
    "application": {
      "applicationId": "amzn1.ask.skill.b4f08937-c3c5-4965-bc61-fe4b7d17365d"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AEZXLYR4I4EXLVVHTW56XRVVZYSGUD6ZRICFWT2TYZ5DTNO7YLY6KRJPGEVV7Z3WTUFRKDL2QSOXU5MWOIWXDWJN4AO2DIfrfr"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.712de816-dcd7-4fbd-8ea9-c07bfb5b875b",
    "locale": "en-US",
    "timestamp": "2016-12-28T17:56:44Z",
    "intent": {
      "name": "main",
      "slots": {
        "pNum": {
          "name": "pNum"
        },
        "pProfile": {
          "name": "pProfile"
        },
        "pUnit": {
          "name": "pUnit"
        },
        "pCommand": {
          "name": "pCommand",
          "value": "repeat"
        },
        "pDevice": {
          "name": "pDevice"
        }
      }
    }
  },
  "version": "1.0"
}` 

Response:
`{
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "There was an error. If this continues to happen, please reach out for help"
    },
    "card": {
      "content": "There was an error. If this continues to happen, please reach out for help",
      "title": "Lambda Error",
      "type": "Simple"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}`

And here is the lambda error log:
```
2016-12-28T17:51:00.474Z	3101513f-cd26-11e6-a469-21dede3635f7	TypeError: Cannot read property 'type' of undefined
at IncomingMessage.<anonymous> (/var/task/index.js:56:30)
at emitOne (events.js:77:13)
at IncomingMessage.emit (events.js:169:7)
at IncomingMessage.Readable.read (_stream_readable.js:360:10)
at flow (_stream_readable.js:743:26)
at resume_ (_stream_readable.js:723:3)
at nextTickCallbackWith2Args (node.js:437:9)
at process._tickDomainCallback (node.js:392:17)
```

**Comment by sbdobrescu** [comment] 2016-12-28 18:11
Thanks for the bug report. I believe the problem is on the ST side. Could you please PM us with the ST log error if any?

**Comment by ngeorgieff** [comment] 2016-12-28 20:28
I've turned debug mode but don't see anything in the ST logs.

**Comment by sbdobrescu** [comment] 2016-12-28 21:36
Ok, are you able to get the main intent to work for anything else? Or Alexa tells you there aas an error and you need to reach out? I am unable to replicate, so I am in the dark as to what is causing Lambda to throw the error...

**Comment by ngeorgieff** [comment] 2016-12-29 20:42
It doesn't work at all. I forgot to mention. It's a fresh install on this ST account. Do you want any specific info or logs?

**Comment by sbdobrescu** [comment] 2017-01-22 13:11
Sorry for the delay in responding. Were you able to get this working? If not, could you please reach out to me on the community via PM so we can troubleshoot live?

**Comment by sbdobrescu** [comment] 2017-02-20 14:27
V4 released. Fresh install required. Please avoid testing repeat last message, as it requires to have a message recorded first. That was a bad example tgat is being addressed in the Wiki.

**Closed as completed by sbdobrescu** 2017-02-20 14:27 UTC
